spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/springdemo?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  freemarker:
    charset: UTF-8
    template-loader-path: classpath:/templates/
    check-template-location: true
    suffix: .ftl
server:
  port: 8888
